### ISSUE TITLE
Compare output of JS & Rust versions of /units-for-slot

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-supermarket#30]
Make sure that the **Market** and **Supermarket** implementations of `/units-for-slot` are aligned and return the same results.

Maybe we could do the following:
- Start the Market server (with the `AdUnit`s & `AdSlot`s that will be used)
- Setup `MockCache` with the same  and the correct **Market** server url that was started

TODOs:

- Make sure this comparison is repeatable (maybe add steps, commands, gist, etc to this issue)
- Seed market and supermarket with the same data
- Compare matching with the rules Channels
- Compare non-matching with the rules Channels

**Comment by simzzz** [comment]
Solution in market: https://github.com/AdExNetwork/adex-market/pull/167

Solution in supermarket: https://github.com/AdExNetwork/adex-supermarket/pull/26/commits/fc5d672829b92ec404a4967cf48d5941d226e72c

I went for the simple ways to just get the output using constant test data. Feedback is appreciated. @elpiel

**Comment by elpiel** [comment]
LGTM, I've left 2 nitpicks and we might look into making a full README, but it's not a priority for this task.

The question I am more concerned - Do the JS & Rust impls actually align?

**Comment by elpiel** [comment]
Since the PRs #37 & https://github.com/AdExNetwork/adex-validator-stack-rust/pull/355 this has been checked and any issues were fixed.

I consider this closed
